# Generated by Django 5.1.4 on 2024-12-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_player_role_invitelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('objective', 'OBJECTIVE'), ('slayer', 'SLAYER'), ('anchor', 'ANCHOR'), ('supporter', 'SUPPORTER')], default='objective', max_length=9),
        ),
    ]
