# Generated by Django 5.1.4 on 2024-12-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_coach_bio_alter_player_bio_alter_player_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='role',
            new_name='is_used',
        ),
        migrations.AlterField(
            model_name='coach',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coach_img'),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('slayer', 'SLAYER'), ('supporter', 'SUPPORTER'), ('anchor', 'ANCHOR'), ('objective', 'OBJECTIVE')], default='objective', max_length=9),
        ),
    ]
