# Generated by Django 5.1.4 on 2024-12-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_player_role_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('anchor', 'ANCHOR'), ('slayer', 'SLAYER'), ('objective', 'OBJECTIVE'), ('supporter', 'SUPPORTER')], default='objective', max_length=9),
        ),
    ]
