# Generated by Django 5.1.4 on 2024-12-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_alter_player_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('objective', 'OBJECTIVE'), ('anchor', 'ANCHOR'), ('slayer', 'SLAYER'), ('supporter', 'SUPPORTER')], default='objective', max_length=9),
        ),
    ]
