# Generated by Django 5.1.4 on 2024-12-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_alter_player_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='teame_b_score',
            new_name='team_b_score',
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('anchor', 'ANCHOR'), ('slayer', 'SLAYER'), ('objective', 'OBJECTIVE'), ('supporter', 'SUPPORTER')], default='objective', max_length=9),
        ),
    ]
