# Generated by Django 5.1.4 on 2024-12-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_rename_teame_b_score_match_team_b_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='deaths',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='kills',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='loses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('slayer', 'SLAYER'), ('supporter', 'SUPPORTER'), ('objective', 'OBJECTIVE'), ('anchor', 'ANCHOR')], default='objective', max_length=9),
        ),
    ]
