# Generated by Django 5.1.4 on 2024-12-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_team_deaths_team_kills_team_loses_team_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('anchor', 'ANCHOR'), ('supporter', 'SUPPORTER'), ('objective', 'OBJECTIVE'), ('slayer', 'SLAYER')], default='objective', max_length=9),
        ),
    ]
