# Generated by Django 5.1.4 on 2024-12-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_alter_player_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('anchor', 'ANCHOR'), ('objective', 'OBJECTIVE'), ('supporter', 'SUPPORTER'), ('slayer', 'SLAYER')], default='objective', max_length=9),
        ),
    ]
