# Generated by Django 5.1.4 on 2024-12-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_newsletter_alter_player_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('slayer', 'SLAYER'), ('anchor', 'ANCHOR'), ('supporter', 'SUPPORTER'), ('objective', 'OBJECTIVE')], default='objective', max_length=9),
        ),
    ]
